### ISSUE TITLE
Ultimate dodge mod reanimated no longer available.

### ISSUE THREAD

**Issue by GarrettFox450** [jdsmith2816/eldersouls#196]
**Describe the bug**
https://www.nexusmods.com/skyrimspecialedition/mods/33049

The ultimate dodge mod reanimated is no longer available.

840.17 - Downloading Missing Archives
840.17 - Missing 1 archives
840.17 - Getting Nexus API Key, if a browser appears, please accept
840.18 - File hash check (-42) 18f9cf397ba9a559658be9942a05aabbe8759b57474186c9172e6ff09f88bbc6
840.18 - Downloading (DMC) The Ultimate Dodge Mod Reanimated-33049-1-1-1585073759.7z
841.59 - Logged into the nexus as redacted
841.6 - Nexus calls remaining: 1436 daily, 100 hourly
842.34 - Wabbajack.Common.Exceptions.HttpException: Http Error Forbidden - Forbidden
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\2\s\Wabbajack.Lib\Http\Client.cs:line 92
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\2\s\Wabbajack.Lib\Http\Client.cs:line 104
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\2\s\Wabbajack.Lib\Http\Client.cs:line 22
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in c:\agent\_work\2\s\Wabbajack.Lib\NexusApi\NexusApi.cs:line 266
842.75 - Trying to find solution to broken download for (DMC) The Ultimate Dodge Mod Reanimated-33049-1-1-1585073759.7z
843.69 - Downloading possible upgrade NexusDownloader+State|SkyrimSpecialEdition|33049|125850

**To Reproduce**
Download the mod from scratch via wabbajack. All goes well except for the ultimate dodge mod. 

**Modlist version**

Most recent as of 12/26/2020

**Did you add any additional mods?**

Negative. Fresh install, adhered to all listed steps.

**Comment by GarrettFox450** [comment]
Disregard saw note about discord
